src/MineServExpo/MainBundle/Entity/Participation.php
<?php

namespace MineServExpo\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Participation
 *
 * @ORM\Table(name="participation")
 * @ORM\Entity(repositoryClass="MineServExpo\MainBundle\Entity\ParticipationRepository")
 */
class Participation
{

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="MineServExpo\UserBundle\Entity\User", inversedBy="participations")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $user;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var $slug
     * @Gedmo\Slug(fields={"name"}, updatable=true, unique=true)
     * @ORM\Column(length=255, unique=true)
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="banner", type="string", length=255)
     */
    private $banner;

    /**
     * @var integer
     *
     * @ORM\Column(name="type", type="integer")
     */
    private $type;

    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status = "0";

    /**
     * @var string
     *
     * @ORM\Column(name="status_detail", type="string", length=255, nullable=true)
     */
    private $statusDetail;

    /**
     * @var integer
     *
     * @ORM\Column(name="server_type", type="integer", nullable=true)
     */
    private $serverType;

    /**
     * @var string
     *
     * @ORM\Column(name="website", type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @var string
     *
     * @ORM\Column(name="youtube", type="string", length=255, nullable=true)
     */
    private $youtube;

    /**
     * @var string
     *
     * @ORM\Column(name="facebook", type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @var string
     *
     * @ORM\Column(name="twitter", type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @var integer
     *
     * @ORM\Column(name="audio_type", type="integer")
     */
    private $audioType;

    /**
     * @var string
     *
     * @ORM\Column(name="audio", type="string", length=255, nullable=true)
     */
    private $audio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $schematicName;

    /**
     * @Assert\File(maxSize="250k")
     */
    public $file;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Participation
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Participation
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Participation
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set banner
     *
     * @param string $banner
     * @return Participation
     */
    public function setBanner($banner)
    {
        $this->banner = $banner;

        return $this;
    }

    /**
     * Get banner
     *
     * @return string
     */
    public function getBanner()
    {
        return $this->banner;
    }

    /**
     * Set type
     *
     * @param integer $type
     * @return Participation
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    public function getTypeText()
    {
        switch ($this->type) {
            case 1:
                $result = 'Youtubeur';
                break;
            case 2:
                $result = 'Site Web';
                break;
            case 0:
            default:
                $result = 'Serveur';
                break;
        }
        return $result;
    }

    /**
     * Set serverType
     *
     * @param integer $serverType
     * @return Participation
     */
    public function setServerType($serverType)
    {
        $this->serverType = $serverType;

        return $this;
    }

    /**
     * Get serverType
     *
     * @return integer
     */
    public function getServerType()
    {
        return $this->serverType;
    }

    public function getServerTypeText()
    {
        switch ($this->serverType) {
            case 0:
                $result = 'Industriel';
                break;
            case 1:
                $result = 'P.V.P.';
                break;
            case 2:
                $result = 'R.P.';
                break;
            case 3:
                $result = 'Semi-R.P.';
                break;
            case 4:
                $result = 'Free Build/Créatif';
                break;
            case 5:
                $result = 'Survie';
                break;
            case 6:
                $result = 'Autre';
                break;
            default:
                $result = '';
                break;
        }
        return $result;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return Participation
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function getStatusText()
    {
        switch ($this->status) {
            case 1:
                $result = 'Non valide';
                break;
            case 2:
                $result = 'Accepté';
                break;
            case 3:
                $result = 'Refusé';
                break;
            case 0:
            default:
                $result = 'En attente';
                break;
        }
        return $result;
    }

    public function isEditable($user)
    {
        if ($this->isOwner($user) && $this->status <= 1) {
            return true;
        }
        return false;
    }

    public function isOwner($user)
    {
        if ($user && is_object($user) && $this->user->getId() == $user->getId()) {
            return true;
        }
        return false;
    }

    /**
     * Set website
     *
     * @param string $website
     * @return Participation
     */
    public function setWebsite($website)
    {
        $this->website = $website;

        return $this;
    }

    /**
     * Get website
     *
     * @return string
     */
    public function getWebsite()
    {
        return $this->website;
    }

    /**
     * Set youtube
     *
     * @param string $youtube
     * @return Participation
     */
    public function setYoutube($youtube)
    {
        $this->youtube = $youtube;

        return $this;
    }

    /**
     * Get youtube
     *
     * @return string
     */
    public function getYoutube()
    {
        return $this->youtube;
    }

    /**
     * Set facebook
     *
     * @param string $facebook
     * @return Participation
     */
    public function setFacebook($facebook)
    {
        $this->facebook = $facebook;

        return $this;
    }

    /**
     * Get facebook
     *
     * @return string
     */
    public function getFacebook()
    {
        return $this->facebook;
    }

    /**
     * Set twitter
     *
     * @param string $twitter
     * @return Participation
     */
    public function setTwitter($twitter)
    {
        $this->twitter = $twitter;

        return $this;
    }

    /**
     * Get twitter
     *
     * @return string
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * Set audioType
     *
     * @param integer $audioType
     * @return Participation
     */
    public function setAudioType($audioType)
    {
        $this->audioType = $audioType;

        return $this;
    }

    /**
     * Get audioType
     *
     * @return integer
     */
    public function getAudioType()
    {
        return $this->audioType;
    }

    /**
     * Set audio
     *
     * @param string $audio
     * @return Participation
     */
    public function setAudio($audio)
    {
        $this->audio = $audio;

        return $this;
    }

    /**
     * Get audio
     *
     * @return string
     */
    public function getAudio()
    {
        return $this->audio;
    }


    /**
     * Set user
     *
     * @param \MineServExpo\UserBundle\Entity\User $user
     * @return Participation
     */
    public function setUser(\MineServExpo\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \MineServExpo\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set statusDetail

src/MineServExpo/MainBundle/Form/SchematicType.php
<?php

namespace MineServExpo\MainBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class SchematicType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file')
            ->add('file', 'file', array(
                'required'  => false,
                'label'  => 'Schematic (généré avec la version spécifiée de WorldEdit)',
            ))
            ->add('save', 'submit', array(
                'label' => 'Uploader'
            ))
        ;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'mineservexpo_mainbundle_schematic';
    }
}

src/MineServExpo/MainBundle/Resources/views/Default/concours.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="content form_default mt10">
        <p class="text-center">
            <img src="{{ asset('bundles/mineservexpomain/images/partners/languagecraft.png') }}">
        </p>

        {% if participation and participation.id %}
            <div class="banner banner-big">
                <h2 class="mce">Vous participez au concours</h2>

                <p>
                    Vous êtes actuellement inscrit avec l'équipe "{{ participation.name }}".<br/>
                    Voici la liste des joueurs de votre équipe:<br/>
                    - {{ participation.user }}<br/>
                    {% if participation.username2 %}
                        - {{ participation.username2 }}<br/>
                    {% endif %}
                    {% if participation.username3 %}
                        - {{ participation.username3 }}<br/>
                    {% endif %}
                    {% if participation.username4 %}
                        - {{ participation.username4 }}<br/>
                    {% endif %}
                </p>

                <p>
                    Vous pouvez modifier votre équipe via le formulaire ci-dessous.
                </p>
            </div>
        {% endif %}

        <h1>Participation au concours de construction</h1>

        <p>
            Les équipes sont composées de 1 à 4 personnes.
        </p>

        {#
        <div>
            <label for="mineservexpo_mainbundle_participation_concours_username1">
                Pseudo Minecraft du joueur n°1 (compte premium seulement) (vous)*
            </label>
            <input type="text" id="mineservexpo_mainbundle_participation_concours_username1"
                   name="mineservexpo_mainbundle_participation_concours[username1]"
                   placeholder="Joueur 1"
                   value="{{ app.user.username }}"
                   disabled="disabled"
                   class="user_skin"/>
        </div>
        #}
        <div class="banner banner-big">
            <h2 class="mce">Inscriptions terminees</h2>

            <p>
                Les inscriptions au concours sont maintenant terminées, merci pour vos participations.<br />
                Rendez-vous sur le serveur construction et teamspeak juste après la cérémonie d'ouverture (24/04 à 20h) pour commencer à construire !
            </p>
        </div>
        {#
            {{ form(form) }}
            * champ obligatoire
        #}
    </div>
    <div class="content">
        <h2>{{ title }}</h2>
        {{ content | raw }}
    </div>
    <script>
        var defaultBannerUrl = "{{ asset('bundles/mineservexpomain/images/img_perview_banner.png') }}";
    </script>
{% endblock %}

src/MineServExpo/MainBundle/Resources/views/Default/exposants.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="content-small search_expo mt30 mb20">
        <div class="row">
            <div class="col-md-4">
                {% if t == 'serveurs' %}
                    <div class="boxed box_inverted box_orange mb10"
                         onclick="document.location = '{{ path('exposants_search',{'q':q, 't':'all'}) }}'">
                        <h3 class="mce txt_center">Serveurs</h3>
                    </div>
                {% else %}
                    <div class="boxed box_inverted box_link mb10"
                         onclick="document.location = '{{ path('exposants_search',{'q':q, 't':'serveurs'}) }}'">
                        <h3 class="mce txt_center">Serveurs</h3>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-4">
                {% if t == 'youtubeurs' %}
                    <div class="boxed box_inverted box_orange mb10"
                         onclick="document.location = '{{ path('exposants_search',{'q':q, 't':'all'}) }}'">
                        <h3 class="mce txt_center">Youtubeurs</h3>
                    </div>
                {% else %}
                    <div class="boxed box_inverted box_link mb10"
                         onclick="document.location = '{{ path('exposants_search',{'q':q, 't':'youtubeurs'}) }}'">
                        <h3 class="mce txt_center">Youtubeurs</h3>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-4">
                {% if t == 'sites-web' %}
                    <div class="boxed box_inverted box_orange"
                         onclick="document.location = '{{ path('exposants_search',{'q':q, 't':'all'}) }}'">
                        <h3 class="mce txt_center">Sites Web</h3>
                    </div>
                {% else %}
                    <div class="boxed box_inverted box_link"
                         onclick="document.location = '{{ path('exposants_search',{'q':q, 't':'sites-web'}) }}'">
                        <h3 class="mce txt_center">Sites Web</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="boxed text-center">
        <form id="search_form">
            <label class="mce" for="q">Exposants:</label>
            <input type="text" value="{{ q }}" size="50" name="q" />
            <input type="hidden" value="{{ t }}" name="t" />
            <input type="submit" class="btn search_expo_submit" value="Rechercher" />
        </form>
    </div>

    {% for participation in pagination %}
        {% include 'MineServExpoMainBundle:Default:participation_partial.html.twig' with {'participation': participation} %}
    {% else %}
        <div class="banner banner-big">
            <h2 class="mce">Exposants</h2>

            <p>Retrouvez bientôt ici la liste des exposants de la MineServ Exposition 2015.</p>

            <p>Vous souhaitez exposer ? Rendez-vous sur la page <a href="{{ path('participer') }}">Participer</a>.</p>
        </div>
    {% endfor %}

    <div class="content-small mb30">
        <div class="text-center mce">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
{% endblock %}

src/MineServExpo/MainBundle/Resources/views/Default/header.html.twig
<header>
    <div class="header_left text-center" target="_blank" style="margin-top:-20px; margin-left:-80px; font-size: 20px;width:300px;">
        <a href="https://client.dedizones.com/link.php?id=40">
            <img src="{{ asset('bundles/mineservexpomain/images/partners/dedizones.png') }}" />
        </a><br />
       Location de VPS et de serveurs Minecraft
    </div>
    <div class="user_profile">
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}

            <div class="user_profile_avatar">
                <img src="{{ path('face_user', { user: app.user.username }) }}"/>
            </div>
            <div class="user_profile_control">
                <a href="{{ path('fos_user_security_logout') }}"><i class="fa fa-power-off"></i></a>
                {{ app.user.username }}<br/>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('sonata_admin_redirect') }}" target="_blank"
                       class="btn btn-xs btn-warning">Admin</a>
                {% endif %}
                <a href="{{ path('fos_user_profile_show') }}" class="btn btn-xs btn-warning">Compte</a>
            </div>
        {% else %}
            <a href="{{ path('fos_user_security_login') }}"
               class="btn btn-warning">{{ 'layout.login'|trans({}, 'FOSUserBundle') }}</a>
            <!--<a href="{{ path('fos_user_registration_register') }}"
               class="btn btn-warning">{{ 'layout.register'|trans({}, 'FOSUserBundle') }}</a>-->
        {% endif %}
        {% for type, messages in app.session.flashbag.all() %}
            {% for key, message in messages %}
                <div class="flash-{{ type }}">
                    {{ message|trans({}, 'FOSUserBundle') }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>
</header>

<div class="logo-container">
    <a href="{{ path('homepage') }}">
        <span class="logo"></span>
    </a>
</div>

<div class="navbar" role="navigation">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{{ path('homepage') }}">Accueil</a></li>
                <li><a href="{{ path('page',{'slug':'informations'}) }}">Informations</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ path('exposants') }}">Exposants</a></li>
                <li><a href="{{ path('page',{'slug':'programme'}) }}">Programme</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="subnav">
    <div class="container">
        <div class="subnavbar navbar-left">
            <a href="ts3server://ts.mineserv-exposition.fr/" class="orange">Teamspeak</a>
        </div>
        <div class="subnavbar navbar-right">
            Nous suivre :
            <a href="http://forum.mineserv-community.fr" target="_blank" title="Forum"><i class="fa fa-comments"></i></a>
            <a href="https://twitter.com/MineServExpo" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a>
            <a href="https://www.facebook.com/MineservCommu" target="_blank" title="Facebook"><i class="fa fa-facebook-square"></i></a>
            <a href="https://www.youtube.com/channel/UCeP-NC0-oriNb4oZyItaMag" target="_blank" title="Youtube"><i class="fa fa-youtube"></i></a>
        </div>
    </div>
</div>

src/MineServExpo/MainBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="content-home">
        <div class="row">
            <div class="col-md-3 text-center mt30">
                {% for partner_name,partner_url in partners1 %}
                    <p>
                        <a href="{{ partner_url }}" target="_blank">
                            <img title="Partenaire: {{ partner_name | capitalize }}"
                                 alt="Partenaire: {{ partner_name | capitalize }}" class="nobanner"
                                 src="{{ asset('bundles/mineservexpomain/images/partners/' ~ partner_name ~ '.png') }}"/>
                        </a>
                    </p>
                {% endfor %}
            </div>
            <div class="col-md-6">
                <div class="boxed mt20 mb20">
                    <div>
                        <div class="banner-left">
                            24 25<br/>
                            26 27<br/>
                            AVRIL<br/>
                            2014<br/>
                        </div>
                        <iframe width="295" height="194" src="//www.youtube.com/embed/ztMD45_z5c4?rel=0" frameborder="0" allowfullscreen></iframe>

                        <div class="clear"></div>
                    </div>
                    <div class="mt5 orange">
                        Serveur: play.mineserv-exposition.fr -
                        <a href="https://minecraft.net/" class="orange" target="_blank" rel="nofollow">Minecraft 1.7.5</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 text-center mt30">
                {% for partner_name,partner_url in partners2 %}
                    <p>
                        <a href="{{ partner_url }}" target="_blank">
                            <img title="Partenaire: {{ partner_name | capitalize }}"
                                 alt="Partenaire: {{ partner_name | capitalize }}" class="nobanner"
                                 src="{{ asset('bundles/mineservexpomain/images/partners/' ~ partner_name ~ '.png') }}"/>
                        </a>
                    </p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="content-ext txt_justify">
        {{ content | raw }}
    </div>
    <div class="content-big">
        <div class="row">
            <div class="col-md-4">
                <div class="boxed box_link" onclick="document.location = '{{ path('page',{'slug':'programme'}) }}'">
                    <img src="{{ asset('bundles/mineservexpomain/images/programme.png') }}"/>

                    <h3 class="mce">Programme</h3>

                    <p>Consultez le programme<br/>de cette année</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="boxed box_link" onclick="document.location = '{{ path('page',{'slug':'informations'}) }}'">
                    <img src="{{ asset('bundles/mineservexpomain/images/informations.png') }}"/>

                    <h3 class="mce">Informations</h3>

                    <p>Règlement et<br/>descriptif de la MSE</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="boxed box_link" onclick="document.location = '{{ path('page',{'slug':'partenaires'}) }}'">
                    <img src="{{ asset('bundles/mineservexpomain/images/partenaires.png') }}"/>

                    <h3 class="mce">Partenaires</h3>

                    <p>Ceux sans qui la MSE<br/>n'existerait pas</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/MineServExpo/MainBundle/Resources/views/Default/page.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="content">
        <h2>{{ title }}</h2>
        {{ content | raw }}
    </div>
{% endblock %}

src/MineServExpo/MainBundle/Resources/views/Default/participation.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="content">
        <h1>{{ participation.name }}</h1>
    </div>

    <div class="banner">
        <img src="{{ participation.banner }}" id="img_perview_banner" width="530" height="150"/>
    </div>

    <div class="content-ext txt_justify">
        <div class="row">
            <div class="col-md-4 text-center participation_links">
                <p class="lettrine mt50 mb50">
                    {{ participation.typeText }}<br/>
                    {% if participation.type == 0 %}
                        Type: {{ participation.serverTypeText }}
                    {% endif %}
                </p>

                <p class="lettrine mt50 mb50">
                    {% if participation.audio %}
                        {% if participation.audioType == 0 %}
                            Teamspeak:<br/>
                            <a href="ts3server://{{ participation.audio }}/">{{ participation.audio }}</a>
                        {% else %}
                            Mumble:<br/>
                            <a href="mumble://{{ participation.audio }}/">{{ participation.audio }}</a>
                        {% endif %}
                    {% endif %}
                </p>
            </div>
            <div class="col-md-4">
                <p class="lettrine">{{ participation.description | nl2br }}</p>
            </div>
            <div class="col-md-4 text-center participation_links">

                {% if participation.website %}
                    <p class="lettrine mt50 mb50">
                        Site web :<br/>
                        <a href="http://{{ participation.website }}" target="_blank" rel="nofollow">
                            http://{{ participation.website }}
                        </a>
                    </p>
                {% endif %}

                {% if participation.twitter or participation.facebook or participation.youtube %}
                    <p class="lettrine mt50 mb50">
                        Réseaux sociaux :<br/>
                        {% if participation.twitter %}
                            <a href="https://twitter.com/{{ participation.twitter }}" target="_blank"
                               rel="nofollow"><i class="fa fa-twitter"></i></a>
                        {% endif %}
                        {% if participation.facebook %}
                            <a href="https://www.facebook.com/{{ participation.facebook }}" target="_blank"
                               rel="nofollow"><i class="fa fa-facebook-square"></i></a>
                        {% endif %}
                        {% if participation.youtube %}
                            <a href="http://www.youtube.com/{{ participation.youtube }}" target="_blank"
                               rel="nofollow"><i class="fa fa-youtube"></i></a>
                        {% endif %}
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="content">
        <p class="text-center">
            Inscrit par {{ participation.user }}
        </p>
    </div>
{% endblock %}

src/MineServExpo/MainBundle/Resources/views/Default/participation_partial.html.twig
<div class="banner banner_expo"
     onclick="document.location = '{{ path('participation', { slug: participation.slug }) }}'">
    <img src="{{ participation.banner }}" id="img_perview_banner" width="530" height="150"/>

    <div class="banner_infos">
        <div class="banner_text">
            {% if participation.isOwner(app.security.getToken().getUser()) %}
                <div class="banner_status verdana float_right">{{ participation.statusText }}</div>
            {% endif %}
            <div class="banner_title mce">{{ participation.name }}</div>
            {% if participation.isEditable(app.security.getToken().getUser()) and participation.statusDetail %}
                <div class="verdana banner_statusdetail">{{ participation.statusDetail }}</div>
            {% endif %}
        </div>

        <div class="banner_btn">
            {% if participation.isEditable(app.security.getToken().getUser()) %}
                <a href="{{ path('participer_edit', { id: participation.id }) }}" class="btn">Modifier</a>
            {% endif %}
            {% if participation.isOwner(app.security.getToken().getUser()) and participation.status == 2 %}
                <a href="{{ path('participer_schematic', { id: participation.id }) }}" class="btn">Schematic</a>
            {% endif %}
        </div>
    </div>
</div>

src/MineServExpo/MainBundle/Resources/views/Default/participations.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    {% for participation in participations %}
        {% include 'MineServExpoMainBundle:Default:participation_partial.html.twig' with {'participation': participation} %}
    {% else %}
        {#
            <div class="banner banner-big">
                <h2 class="mce">Avis aux participants</h2>

                <p>
                    Avant de vous inscrire, il vous est conseillé de vous informer sur les règles qui régieront votre
                    participations dans la section informations.
                </p>
            </div>
        #}
        <div class="banner banner-big">
            <h2 class="mce">Inscriptions terminees</h2>

            <p>
                Les inscriptions exposants sont maintenant terminées, merci pour vos participations.
            </p>
        </div>
    {% endfor %}
    {#
        <div class="banner banner-big box_link" onclick="document.location = '{{ path('participer') }}'">
            <h2 class="mce">Nouvelle participation</h2>

            <p>S'inscrire en tant qu'exposant de la MSE 2014</p>
        </div>
    #}
{% endblock %}

src/MineServExpo/MainBundle/Resources/views/Default/participerForm.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="content form_default">
        <h1>Formulaire de participation</h1>
        {{ form(form) }}
        <p class="mt20 text-center">
            En vous inscrivant, vous déclarez accepter le
            <a href="{{ path('page',{'slug':'reglement'}) }}">règlement</a>
        </p>
    </div>
    <script>
        var defaultBannerUrl = "{{ asset('bundles/mineservexpomain/images/img_perview_banner.png') }}";
    </script>
{% endblock %}